version: '3'

services:
  zookeeper-server:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'


  kafka-server:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181

  redis-server:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  vuz-task:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_PROVIDER_HOST: ${EMAIL_PROVIDER_HOST}
      EMAIL_PROVIDER_USER: ${EMAIL_PROVIDER_USER}
      EMAIL_PROVIDER_PASSWORD: ${EMAIL_PROVIDER_PASSWORD}
      EMAIL_PROVIDER_PORT: ${EMAIL_PROVIDER_PORT}
    depends_on:
      - redis-server
      - kafka-server
      - zookeeper-server